services:

  client:
    image: satyam3singh/client-app:${BUILD_NUMBER}
    container_name: client-app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://54.204.67.134:5000   # <-- FIXED
    depends_on:
      - server

  server:
    image: satyam3singh/server-app:${BUILD_NUMBER}
    container_name: server-app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://satyamsinghbhardwaj72_db_user:rgmkp09sWTVDpFf3@cluster0.tpy17ux.mongodb.net/mydb